PYTHON ?= python3
QUICKSILVER_RUNTIME_DIR ?= .quicksilver-runtime
PYTHONPYCACHEPREFIX ?= $(CURDIR)/$(QUICKSILVER_RUNTIME_DIR)/pycache

.PHONY: test quick-validate validate demo

test:
	QUICKSILVER_RUNTIME_DIR=$(QUICKSILVER_RUNTIME_DIR) PYTHONPYCACHEPREFIX=$(PYTHONPYCACHEPREFIX) $(PYTHON) -m pytest tests/ -q -o cache_dir=$(QUICKSILVER_RUNTIME_DIR)/pytest-cache

demo:
	QUICKSILVER_RUNTIME_DIR=$(QUICKSILVER_RUNTIME_DIR) PYTHONPYCACHEPREFIX=$(PYTHONPYCACHEPREFIX) $(PYTHON) -m quicksilver demo all

quick-validate:
	QUICKSILVER_RUNTIME_DIR=$(QUICKSILVER_RUNTIME_DIR) PYTHONPYCACHEPREFIX=$(PYTHONPYCACHEPREFIX) $(PYTHON) -m quicksilver quick-validate

validate: quick-validate
